name: 'Create Readme'
on:
  push:
    branches:
      - master

jobs:
  create-readme:
    name: 'create-readme'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Set up Python 3.7.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 'Create readme'
        uses: 'clouddrove/github-actions@v4.0'
        with:
          actions_subcommand: 'readme'



      - name: pre-commit check errors
        uses: pre-commit/action@v2.0.0
        continue-on-error: true

      - name: pre-commit fix erros
        uses: pre-commit/action@v2.0.0
        continue-on-error: true

      - name: 'push readme'
        uses: 'clouddrove/github-actions@v4.0'
        continue-on-error: true
        with:
          actions_subcommand: 'push'
      
